name: Deploy on Prod Release

on:
  release:
    types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PRINT RELEASE DATA
        id: check_release
        run: |
          if [ "${{ github.event.release.tag_name }}" != "prod" ]; then
            echo "This is not a 'prod' release."
            exit 1
          fi

          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)

          if [ "${{ github.event.release.tag_name }}" != "$LATEST_RELEASE" ]; then
            echo "This is not the latest release."
            exit 1
          fi

          echo "This is the latest 'prod' release."

      - name: Deploy
        if: success()
        run: |
          echo "Deploying the latest 'prod' release."
          # Add your deployment script here
